from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.enum.text import PP_ALIGN
from pptx.dml.color import RGBColor
import os

# Source and Destination
SOURCE_PPTX = "/Users/ashishb/Documents/cap/ppt/NYC-Citi-Bike-Project-Presentation.pptx"
OUTPUT_PPTX = "/Users/ashishb/Documents/cap/NYC_Citi_Bike_Project_Final_Presentation.pptx"

# Image Paths
IMAGES = {
    "architecture": "/Users/ashishb/.gemini/antigravity/brain/47521311-833e-4118-b37a-190fd352baf3/architecture_diagram_1765490065515.png",
    "map": "/Users/ashishb/.gemini/antigravity/brain/47521311-833e-4118-b37a-190fd352baf3/map_3d_viz_1765490079894.png",
    "station": "/Users/ashishb/.gemini/antigravity/brain/47521311-833e-4118-b37a-190fd352baf3/station_analytics_ui_1765490093801.png",
    "neural": "/Users/ashishb/.gemini/antigravity/brain/47521311-833e-4118-b37a-190fd352baf3/neural_network_ai_1765490107079.png",
    "route": "/Users/ashishb/.gemini/antigravity/brain/47521311-833e-4118-b37a-190fd352baf3/route_network_flow_1765490121023.png",
    "fleet": "/Users/ashishb/.gemini/antigravity/brain/47521311-833e-4118-b37a-190fd352baf3/fleet_command_dashboard_1765490136464.png"
}

def create_presentation():
    # Load the template
    if os.path.exists(SOURCE_PPTX):
        prs = Presentation(SOURCE_PPTX)
        print(f"Loaded template from {SOURCE_PPTX}")
    else:
        print("Template not found, starting fresh.")
        prs = Presentation()

    # Clear existing slides
    for i in range(len(prs.slides) - 1, -1, -1):
        rId = prs.slides._sldIdLst[i].rId
        prs.part.drop_rel(rId)
        del prs.slides._sldIdLst[i]

    # Helper to add slide manually
    def add_slide(title_text, content_bullets, image_path=None):
        # Use Layout 1 (Slide 1 master)
        slide_layout = prs.slide_layouts[1] if len(prs.slide_layouts) > 1 else prs.slide_layouts[0]
        slide = prs.slides.add_slide(slide_layout)
        
        # Add Title Text Box
        left = Inches(0.5)
        top = Inches(0.4)
        width = Inches(9)
        height = Inches(1)
        
        title_box = slide.shapes.add_textbox(left, top, width, height)
        tf = title_box.text_frame
        tf.word_wrap = True
        p = tf.add_paragraph()
        p.text = title_text
        p.font.size = Pt(36) # Slightly smaller to fit logo
        p.font.bold = True
        p.font.color.rgb = RGBColor(0, 0, 0)
        p.alignment = PP_ALIGN.LEFT
        
        # Determine Layout based on image
        if image_path and os.path.exists(image_path):
            # Split Layout: Text Left, Image Right
            text_left = Inches(0.5)
            text_top = Inches(1.5)
            text_width = Inches(5.5)
            text_height = Inches(5.0)
            
            img_left = Inches(6.2)
            img_top = Inches(1.8)
            img_width = Inches(3.5)
            # Image height auto based on aspect ratio usually, but we can constrain width
            
            slide.shapes.add_picture(image_path, img_left, img_top, width=img_width)
            
        else:
            # Full Width Text
            text_left = Inches(0.5)
            text_top = Inches(1.5)
            text_width = Inches(9)
            text_height = Inches(5.5)
        
        content_box = slide.shapes.add_textbox(text_left, text_top, text_width, text_height)
        tf = content_box.text_frame
        tf.word_wrap = True
        
        # Add bullets
        first = True
        for bullet in content_bullets:
            p = tf.add_paragraph() if not first else tf.paragraphs[0]
            p.text = bullet
            p.font.size = Pt(18)
            p.space_after = Pt(12)
            if bullet.startswith("-"):
                 p.level = 1
                 p.text = bullet[1:].strip() 
            else:
                 p.level = 0
            first = False

    # ---------------- SLIDE CONTENT ----------------

    # Slide 1: Title Slide (Custom Layout)
    slide_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(slide_layout)
    
    left = Inches(1)
    top = Inches(2.5)
    width = Inches(8)
    height = Inches(2)
    tx = slide.shapes.add_textbox(left, top, width, height)
    tf = tx.text_frame
    p = tf.paragraphs[0]
    p.text = "NYC Citi Bike Analytics"
    p.font.size = Pt(54)
    p.font.bold = True
    p.alignment = PP_ALIGN.CENTER
    
    top = Inches(3.5)
    tx = slide.shapes.add_textbox(left, top, width, height)
    tf = tx.text_frame
    p = tf.paragraphs[0]
    p.text = "A Big Data Exploratory Analysis & Advanced Interactive Dashboard\nGenerated by Antigravity"
    p.font.size = Pt(24)
    p.font.color.rgb = RGBColor(80, 80, 80)
    p.alignment = PP_ALIGN.CENTER

    # Slide 2: Executive Summary
    add_slide("Executive Summary", [
        "Objective: Revolutionize urban mobility analysis using Big Data & AI.",
        "Scope: Comprehensive dashboard for NYC Citi Bike system (millions of trips).",
        "Key Innovation: Real-time geospatial visualization + Neural Demand forecasting.",
        "Impact: Enables data-driven decisions for fleet rebalancing and planning.",
        "Target Audience: City planners, operations managers, and data scientists."
    ])

    # Slide 3: System Architecture (With Image)
    add_slide("System Architecture Overview", [
        "Modern Full-Stack Application:",
        "- Frontend: React 18, Vite, Tailwind CSS (Glassmorphism Design).",
        "- Visualization: Deck.gl (3D Hexagon/Heatmaps), Recharts.",
        "- Backend: FastAPI (Python) for high-performance REST endpoints.",
        "- Data Layer: Optimized data loading, Pandas/NumPy processing.",
        "- AI Layer: PyTorch/TensorFlow based LSTM & CNN models."
    ], IMAGES["architecture"])

    # Slide 4: Data Ingestion & Processing
    add_slide("Data Pipeline & Methodology", [
        "Scale: Handling massive historical trip datasets (CSV/Parquet).",
        "Preprocessing steps:",
        "- Cleaning null values & anomalies.",
        "- Spatial aggregation (Hexagon binning).",
        "- Temporal aggregation (Hourly traffic patterns).",
        "Optimization: Efficient filtering by trip duration and user type.",
        "Result: High-speed query performance for the dashboard."
    ])

    # Slide 5: Map Explorer (With Image)
    add_slide("Map Explorer: 3D Geospatial Intelligence", [
        "Core Feature: Advanced 3D visualization of station activity.",
        "Modes:",
        "- 3D Hex Density: Aggregated trip volume visualization.",
        "- Heatmaps: Identification of high-activity hot zones.",
        "- Points: Individual station status with rich tooltips.",
        "Interactivity: Tilt, zoom, and dynamic tooltips.",
        "Tech: High-performance WebGL rendering via Deck.gl."
    ], IMAGES["map"])

    # Slide 6: Station Intel (With Image)
    add_slide("Station Intel: Deep Dive Analytics", [
        "Detailed Profile: Granular analysis of individual stations.",
        "Metrics:",
        "- Inbound vs. Outbound trip distribution.",
        "- Peak hour identification.",
        "- Connectivity rankings (top sourced/destined connections).",
        "Visualization: Radar charts for temporal patterns.",
        "Utility: Pinpoints operational bottlenecks."
    ], IMAGES["station"])

    # Slide 7: Neural Demand Lab (With Image)
    add_slide("Neural Demand Lab: AI Forecasting", [
        "Goal: Predict future bike availability and demand.",
        "Models:",
        "- CNN (Convolutional Neural Networks) for spatial patterns.",
        "- LSTM (Long Short-Term Memory) for temporal sequences.",
        "Features: Training on historical usage and weather.",
        "Output: Accurate demand forecasts to preempt stockouts."
    ], IMAGES["neural"])

    # Slide 8: Route Explorer (With Image)
    add_slide("Route Explorer: Network Flow", [
        "Visualization: Tracing popular travel corridors.",
        "Insights:",
        "- Identification of major commuter arteries.",
        "- Cross-borough traffic analysis.",
        "- Usage duration vs. distance correlation.",
        "Application: Helps in planning new bike lane infrastructure.",
        "Feature: Comparison of casual vs. member routes."
    ], IMAGES["route"])

    # Slide 9: Fleet Command (With Image)
    add_slide("Fleet Command: Strategic Rebalancing", [
        "Operational Dashboard: Specialized view for logistics teams.",
        "Critical Alerts: identifying stations with <10% availability.",
        "Optimization: Suggestions for moving bikes from overflow to empty.",
        "Efficiency: Maximizes fleet utilization and reduces lost revenue."
    ], IMAGES["fleet"])

    # Slide 10: UX Design Philosophy
    add_slide("Premium UX/UI Design", [
        "Aesthetics: 'Glassmorphism' style with deep dark mode.",
        "Clarity: High-contrast data visualizations for readability.",
        "Feedback: Rich interactive elements (pulsing markers, hover effects).",
        "Goal: To provide an enterprise-grade, polished analytical tool."
    ])

    # Slide 11: Challenges & Technical Solutions",
    add_slide("Technical Challenges Solved", [
        "Challenge 1: Rendering 2000+ interactive 3D objects smoothy.",
        "- Solution: WebGL instancing via Deck.gl and optimized React memos.",
        "Challenge 2: Large dataset latency.",
        "- Solution: Backend pre-aggregation and efficient JSON payloads.",
        "Challenge 3: Complex layout management.",
        "- Solution: Modular component architecture and sidebar navigation."
    ])

    # Slide 12: Future Roadmap
    add_slide("Future Roadmap & Conclusion", [
        "Real-Time Integration: Live feed from Citi Bike GBMFS API.",
        "Weather API: dynamic model adjustment based on live rain/snow data.",
        "Mobile App: Companion app for field rebalancing teams.",
        "User Personalization: Saved routes and dashboard views.",
        "Conclusion: A scalable, robust platform for modern urban mobility."
    ])

    # Save
    prs.save(OUTPUT_PPTX)
    print(f"Presentation saved to {OUTPUT_PPTX}")

if __name__ == "__main__":
    create_presentation()
